server:
  tomcat:
    threads:
      max: 200
      min-spare: 20
  port: 18082

spring:
  application:
    name: file
  threads:
    virtual:
      enabled: true
  profiles:
    include: local

trace:
  context:
    mapping:
      # key(别名) : value(真实Header)
      OrderId: X-Order-Id
      UserId: X-User-Id
      BizId: X-Biz-Id
      BatchId: X-Batch-Id
