-- =============================================================================
-- shared-event-starter - PostgreSQL Schema
-- =============================================================================
-- 领域事件存储与分发日志表（纯技术表，使用 NOW() 管理时间戳）
--
-- 设计要点：
--   1. sys_event_store 以 event_id 为主键，存储领域事件原始 payload 与集成事件 payload
--   2. sys_event_dispatch_log 记录每个事件在各分发通道的执行状态，支持补偿重试
--   3. 此表为基础设施内部实现，不经过 DO/Converter，使用原生 JDBC 操作
--   4. 时间戳由数据库 NOW() 管理（符合 06-数据库规范.md 第十节例外情况）
-- =============================================================================

-- -----------------------------------------------------------------------------
-- 1. 领域事件存储表
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sys_event_store (
    event_id            VARCHAR(64)   NOT NULL,
    event_type          VARCHAR(255)  NOT NULL,
    integration_type    VARCHAR(64),
    occurred_on         TIMESTAMP     NOT NULL,
    domain_payload      TEXT          NOT NULL,
    integration_payload TEXT,
    created_at          TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (event_id)
);

CREATE INDEX IF NOT EXISTS idx_sys_event_store_event_type     ON sys_event_store(event_type);
CREATE INDEX IF NOT EXISTS idx_sys_event_store_occurred_on    ON sys_event_store(occurred_on);
CREATE INDEX IF NOT EXISTS idx_sys_event_store_integration    ON sys_event_store(integration_type);

COMMENT ON TABLE  sys_event_store IS '领域事件存储表';
COMMENT ON COLUMN sys_event_store.event_id IS '事件ID（EventId，主键）';
COMMENT ON COLUMN sys_event_store.event_type IS '领域事件类型名';
COMMENT ON COLUMN sys_event_store.integration_type IS '集成事件类型名（NULL 表示无集成事件）';
COMMENT ON COLUMN sys_event_store.occurred_on IS '事件发生时间';
COMMENT ON COLUMN sys_event_store.domain_payload IS '领域事件 JSON 序列化内容';
COMMENT ON COLUMN sys_event_store.integration_payload IS '集成事件 JSON 序列化内容（NULL 表示无集成事件）';
COMMENT ON COLUMN sys_event_store.created_at IS '记录创建时间';

-- -----------------------------------------------------------------------------
-- 2. 事件分发日志表（记录每个事件在各通道的分发状态，支持补偿重试）
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS sys_event_dispatch_log (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    event_id        VARCHAR(64)  NOT NULL,
    channel         VARCHAR(100) NOT NULL,
    status          VARCHAR(20)  NOT NULL,
    error_msg       TEXT,
    retry_count     INT          DEFAULT 0,
    next_retry_at   TIMESTAMP,
    created_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,

    PRIMARY KEY (id),
    CONSTRAINT uq_event_channel UNIQUE (event_id, channel)
);

CREATE INDEX IF NOT EXISTS idx_sys_event_dispatch_log_status       ON sys_event_dispatch_log(status);
CREATE INDEX IF NOT EXISTS idx_sys_event_dispatch_log_next_retry   ON sys_event_dispatch_log(next_retry_at);
CREATE INDEX IF NOT EXISTS idx_sys_event_dispatch_log_retry_count  ON sys_event_dispatch_log(retry_count);

COMMENT ON TABLE  sys_event_dispatch_log IS '事件分发日志表';
COMMENT ON COLUMN sys_event_dispatch_log.id IS '自增主键（技术日志表，非业务表）';
COMMENT ON COLUMN sys_event_dispatch_log.event_id IS '关联事件ID';
COMMENT ON COLUMN sys_event_dispatch_log.channel IS '分发通道: SPRING/REDIS/ROCKETMQ';
COMMENT ON COLUMN sys_event_dispatch_log.status IS '分发状态: PENDING/SUCCESS/FAILED';
COMMENT ON COLUMN sys_event_dispatch_log.error_msg IS '失败错误信息（最多 500 字符）';
COMMENT ON COLUMN sys_event_dispatch_log.retry_count IS '已重试次数（上限 10）';
COMMENT ON COLUMN sys_event_dispatch_log.next_retry_at IS '下次重试时间';
COMMENT ON COLUMN sys_event_dispatch_log.created_at IS '记录创建时间';
COMMENT ON COLUMN sys_event_dispatch_log.updated_at IS '记录更新时间';
