<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.example</groupId>
    <artifactId>demo-shared</artifactId>
    <version>1.0-SNAPSHOT</version>
  </parent>

  <artifactId>shared-lib</artifactId>
  <packaging>pom</packaging>

  <modules>
    <module>shared-types</module>
    <module>shared-exception</module>
    <module>shared-domain</module>
    <module>shared-api</module>
    <module>shared-utils</module>
    <module>shared-crypto</module>
    <module>shared-json</module>
    <module>shared-lock</module>
    <module>gateway-shared</module>
    <module>bff-shared</module>
  </modules>
</project>
