package com.example.shared.event.store;

import com.example.shared.domain.event.DomainEvent;
import com.example.shared.domain.event.EventStore;
import com.example.shared.primitives.identity.EventId;
import com.fasterxml.jackson.databind.ObjectMapper;
import com.fasterxml.jackson.datatype.jsr310.JavaTimeModule;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.jdbc.datasource.DriverManagerDataSource;

import javax.sql.DataSource;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

import static org.assertj.core.api.Assertions.assertThat;

class JdbcEventStoreTest {

    private JdbcEventStore eventStore;
    private JdbcClient jdbcClient;

    @BeforeEach
    void setUp() {
        DataSource ds = new DriverManagerDataSource(
            "jdbc:h2:mem:event_test;MODE=PostgreSQL;DB_CLOSE_DELAY=-1", "sa", "");
        jdbcClient = JdbcClient.create(ds);
        initSchema();
        eventStore = new JdbcEventStore(jdbcClient, new ObjectMapper().registerModule(new JavaTimeModule()));
    }

    private void initSchema() {
        jdbcClient.sql("DROP TABLE IF EXISTS sys_event_dispatch_log").update();
        jdbcClient.sql("DROP TABLE IF EXISTS sys_event_store").update();
        jdbcClient.sql("""
            CREATE TABLE sys_event_store (
              event_id VARCHAR(64) PRIMARY KEY,
              event_type VARCHAR(255) NOT NULL,
              integration_type VARCHAR(64),
              occurred_on TIMESTAMP NOT NULL,
              domain_payload TEXT NOT NULL,
              integration_payload TEXT,
              created_at TIMESTAMP
            )""").update();
        jdbcClient.sql("""
            CREATE TABLE sys_event_dispatch_log (
              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
              event_id VARCHAR(64) NOT NULL,
              channel VARCHAR(100) NOT NULL,
              status VARCHAR(20) NOT NULL,
              error_msg TEXT,
              retry_count INT DEFAULT 0,
              next_retry_at TIMESTAMP,
              created_at TIMESTAMP,
              updated_at TIMESTAMP,
              CONSTRAINT uq_event_channel UNIQUE (event_id, channel)
            )""").update();
    }

    @Test
    void should_save_both_domain_and_integration_payload() {
        TestDomainEvent event = new TestDomainEvent(EventId.generate(), LocalDateTime.now(), "hello");
        Map<String, Object> integrationEvent = Map.of("data", "hello");

        eventStore.save(event, integrationEvent, "TestDomainEvent");

        Long count = jdbcClient.sql("SELECT COUNT(*) FROM sys_event_store WHERE event_id = ?")
            .param(event.eventId().toString())
            .query(Long.class).single();
        assertThat(count).isEqualTo(1L);
    }

    @Test
    void findPendingLogs_should_return_integration_payload_not_domain_payload() {
        TestDomainEvent event = new TestDomainEvent(EventId.generate(), LocalDateTime.now(), "hello");
        eventStore.save(event, Map.of("data", "hello"), "TestDomainEvent");
        long logId = eventStore.initDispatchLog(event.eventId().toString(), "rocketmq");

        List<EventStore.PendingEntry> entries = eventStore.findPendingLogs(10);

        assertThat(entries).hasSize(1);
        EventStore.PendingEntry entry = entries.get(0);
        assertThat(entry.logId()).isEqualTo(logId);
        assertThat(entry.integrationType()).isEqualTo("TestDomainEvent");
        // 集成事件应能被反序列化为 Map（不依赖具体类）
        assertThat(entry.integrationEvent()).isInstanceOf(java.util.Map.class);
    }

    record TestDomainEvent(EventId eventId, LocalDateTime occurredOn, String data) implements DomainEvent {}
}
