<?xml version="1.0" encoding="UTF-8"?>
<project xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xmlns="http://maven.apache.org/POM/4.0.0"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.example</groupId>
    <artifactId>auth-service</artifactId>
    <version>1.0-SNAPSHOT</version>
  </parent>
  <artifactId>auth-adapter</artifactId>
  <dependencies>
    <dependency>
      <groupId>com.example</groupId>
      <artifactId>auth-api</artifactId>
    </dependency>
    <dependency>
      <groupId>com.example</groupId>
      <artifactId>auth-application</artifactId>
    </dependency>
    <dependency>
      <groupId>com.example</groupId>
      <artifactId>shared-web-starter</artifactId>
    </dependency>
    <!-- shared-permission-starter: @RequirePermission 切面 + PermissionExecutor 接口 -->
    <dependency>
      <groupId>com.example</groupId>
      <artifactId>shared-permission-starter</artifactId>
    </dependency>
    <dependency>
      <groupId>org.mapstruct</groupId>
      <artifactId>mapstruct</artifactId>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <scope>provided</scope>
    </dependency>
  </dependencies>
</project>
