server:
  tomcat:
    threads:
      max: 200
      min-spare: 20
  port: 18083

spring:
  application:
    name: file-service
  threads:
    virtual:
      enabled: true
  http:
    client:
      factory: http-components
      pool:
        max-total: 100
        max-per-route: 20
        validate-after-inactivity: 5s
      settings:
        connect-timeout: 3s
        read-timeout: 30s
        connection-time-to-live: 30s
  profiles:
    include: local

mybatis-flex:
  mapper-locations: classpath*:/mapper/**/*.xml

shared:
  cache:
    mode: L1_ONLY
    rules:
      segment_buffer:
        mode: L1_ONLY
        ttl: 24h

trace:
  context:
    mapping:
      OrderId: X-Order-Id
      UserId: X-User-Id
      BizId: X-Biz-Id
      BatchId: X-Batch-Id

logging:
  file:
    path: /applog/${spring.application.name}
    name: ${spring.application.name}.log
  logback:
    rollingpolicy:
      total-size-cap: 1GB
      max-history: 30
